// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU56yf-EHZsPCg8M7_bMdy5PD_tDIGiXQ',
    appId: '1:339518401619:web:4b91944a85e5dbeaf8aaa6',
    messagingSenderId: '339518401619',
    projectId: 'saferbe',
    authDomain: 'saferbe.firebaseapp.com',
    storageBucket: 'saferbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8HpTxN5hRVLohh5IcxzEooNj6uOSlWs',
    appId: '1:339518401619:android:922bb482e35a31dbf8aaa6',
    messagingSenderId: '339518401619',
    projectId: 'saferbe',
    storageBucket: 'saferbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdaGgZonOvw1yITPwyR0TTGJrDA14Zi7g',
    appId: '1:339518401619:ios:3d05ec62940d4469f8aaa6',
    messagingSenderId: '339518401619',
    projectId: 'saferbe',
    storageBucket: 'saferbe.firebasestorage.app',
    iosBundleId: 'com.darkNode.saferBe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdaGgZonOvw1yITPwyR0TTGJrDA14Zi7g',
    appId: '1:339518401619:ios:3d05ec62940d4469f8aaa6',
    messagingSenderId: '339518401619',
    projectId: 'saferbe',
    storageBucket: 'saferbe.firebasestorage.app',
    iosBundleId: 'com.darkNode.saferBe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU56yf-EHZsPCg8M7_bMdy5PD_tDIGiXQ',
    appId: '1:339518401619:web:7b22a245f554938df8aaa6',
    messagingSenderId: '339518401619',
    projectId: 'saferbe',
    authDomain: 'saferbe.firebaseapp.com',
    storageBucket: 'saferbe.firebasestorage.app',
  );
}
